### PR TITLE
Update image and manifests for v1.8

### PR DESCRIPTION
**Pull request by misohu**
No changes in manifests

Fixed image based on https://github.com/kubeflow/manifests/pull/2567/files

### CODE REVIEW

**Review by NohaIhab — COMMENTED** [review]
A couple changes missing here:
* a change in the `viewer-spec.yaml` [see upstream](https://github.com/kubeflow/manifests/blob/v1.8.0/apps/volumes-web-app/upstream/base/viewer-spec.yaml)
* the image tag of the filebrowser image was changed to `v2.23.0` [see upstream](https://github.com/kubeflow/manifests/blob/v1.8.0/apps/volumes-web-app/upstream/base/deployment.yaml#L24)

**Comment by ca-scribner** [comment]
Ready for re-review, but the integration tests are failing and I'm not sure why

**Review by NohaIhab — COMMENTED** [review]
thanks @ca-scribner 
the tests are failing because we need to change tests/integration/config-map.yaml to match the changes in src/templates/viewer-spec.yaml.j2

**Review by NohaIhab — APPROVED** [review]
LGTM

**Pull request merged**
